# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='location',
            field=models.CharField(default='pictures', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to=portfolio.models.user_directory_path),
        ),
    ]
