# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20151210_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='location',
            field=models.CharField(choices=[('blog', 'Blog'), ('pictures', 'Pictures'), ('commisioned', 'Commisioned')], max_length=50),
        ),
    ]
